add Transmittable persistance operations
ideacrew/crm_gateway pull request #44
Opened 2024-07-15 20:36 UTC by jacobkagon

https://www.pivotaltracker.com/n/projects/2640060/stories/187939070

2024-07-16 22:20 UTC, saikumar9 requested changes

2024-07-16 22:20 UTC, saikumar9 commented on app/domain/operations/transmittable/generate_request_objects.rb
> +module Operations
@jacobkagon I recommend you to nest this under the SugarCRM namespace as this is not a generic operation.

2024-07-16 22:20 UTC, saikumar9 commented on app/domain/operations/transmittable/generate_request_objects.rb
> +        @transaction = yield create_request_transaction(transaction_params, @job)
@jacobkagon We discussed having multiple transactions, one for the Account and one per contact. I do not see that here.

2024-07-16 22:20 UTC, saikumar9 commented on app/domain/operations/transmittable/generate_request_objects.rb
> +          }
I do not see the payload being persisted on the transaction here. We have to either save the account or contact related payload accordingly.

2024-07-16 22:20 UTC, saikumar9 commented on app/domain/operations/transmittable/generate_request_objects.rb
> +      end
This method is not being used anywhere.

2024-07-16 22:20 UTC, saikumar9 commented on app/domain/operations/families/create.rb
> +            correlation_id: values[:inbound_family_cv][:hbx_id],
The correlation_id should be a unique secure random string generated and set from EA to Crm per my understanding. Please review and make changes if required.

2024-07-16 22:20 UTC, saikumar9 commented on spec/domain/operations/families/create_spec.rb
> +RSpec.describe Operations::Families::Create, dbclean: :after_each do
Good test coverage.

2024-07-16 22:23 UTC, saikumar9 commented on spec/domain/operations/families/updated_or_created_processor_spec.rb
> +  describe "Success" do
@jacobkagon For the success case we can verify the below:
* Check if the persistence objects are being created properly.
* Check if we can navigate between objects (transmittable and the subject) using the associations properly.

2024-07-18 14:43 UTC, saikumar9 approved these changes
LGTM!

2024-07-18 15:57 UTC, jayreddy519 commented on Gemfile.lock
> +  rexml (~> 3.3.2)
changed rexml version.

2024-07-18 16:03 UTC, jayreddy519 commented on spec/domain/operations/sugar_crm/transmittable/generate_request_objects_spec.rb
> +        expect(@result.failure).to eql("Inbound family cv payload not present")
good spec coverage for positive & negative cases.

2024-07-18 16:54 UTC, jayreddy519 approved these changes
lgtm.

2024-07-18 17:12 UTC, merged