add missing indexes
ideacrew/crm_gateway pull request #56
Opened 2024-08-01 18:15 UTC by jacobkagon

https://www.pivotaltracker.com/n/projects/2640060/stories/187999235

2024-08-01 18:32 UTC, saikumar9 requested changes

2024-08-01 18:32 UTC, saikumar9 commented on app/models/transmittable/transaction.rb
> +    index({ transactable_id: 1 })
https://github.com/ideacrew/crm_gateway/pull/56/files#diff-5a55385eb24f602100826a1002e810ffcc6fb112dcfef029d71e0477015fc4f0R17 should already cover the indexes for `transactable_id` and `transactable_type`. Please verify.

2024-08-01 21:29 UTC, saikumar9 approved these changes

2024-08-02 13:41 UTC, jayreddy519 approved these changes
updated to_time with DateTime, lgtm.

2024-08-02 13:41 UTC, merged